name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - '*'  # Deploy previews for all pull requests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        app_location: "." 
        azure_static_web_apps_api_token: ${{ secrets.FLUTTER_TEST_AZURE_STATIC_WEB_APPS_API_TOKEN }}
